In [1]:
import numpy as np

In [ ]:
np.__version__

## 1. 建立 NumPy array (陣列)
### 1.1 array() 函式
使用 array() 函式，可將 Python list 或元組 (tuple) 的值建立為 NumPy array。

In [5]:
# use list
a = np.array([1, 2, 3, 4, 5])

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
# use tuple
b = np.array((6, 7, 8))

In [8]:
type(b)

numpy.ndarray

### 1.2 使用 arange() 與 linspace() 函式產生等差一維陣列
要用序列數字產生陣列元素的話，可以使用 arange() 函式，arange() 函式引數如下，其中結束值為必輸，起始值、間隔值非必輸。產生的序列數字包含起始值但不包含結束值，也就是 [start, stop) 的表示方式。
> numpy.arange([start, ]stop, [step, ]dtype=None)

跟 arange() 的用法很類似，呼叫 linspace() 時的引數有啟始值、結束值、資料型別 dtype。
與 arange() 不同的地方在於起始跟結束值都是必輸，產生該範圍內等分的數值，另外對於產生的元素也可以有更多的控制：

+ num：產生元素數
+ endpoint:是否包含結束值
+ retstep：是否要顯示間隔值，間隔值是依照啟始值、結束值、產生元素數計算而得
+ axis：產生依據的軸
+ linspace() 函式的定義：
> numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [9]:
#  2, 4, 6, 8 int
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [10]:
np.arange(1.0, 3.0, 0.5, dtype='float64')

array([1. , 1.5, 2. , 2.5])

In [12]:
b = np.arange(0.12, 0.16, step=0.01)
print("including ending value:", b)

including ending value: [0.12 0.13 0.14 0.15 0.16]


## 1.3 建立多維陣列
要建立多維陣列，簡單的理解方式就是陣列中的元素也是陣列，呼叫 array() 函式時，只要將 list 中的元素也是 list 傳入即可。下面的例子是建立二維陣列。

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


## 1.4 zeros()、ones()、empty()
呼叫 zeros()、ones()函式，可以依照傳入的形狀引數，建立元素全為 0、全為 1 的陣列。

empty() 則是不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定。

In [14]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a = np.arange(0,21,1)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [22]:
#2.呈上題，將以上數列取出偶數。
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
#3.呈1題，將數列取出3的倍數。
a[3::3]

array([ 3,  6,  9, 12, 15, 18])