In [1]:
import numpy as np

 題目:
#### 1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
#### 2.呈上題的array，找出被6除餘1的數的索引

In [4]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))

In [5]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
b = array1.reshape(6,5).ravel(order = 'F')

In [20]:
b

array([ 0,  5, 10, 15, 20, 25,  1,  6, 11, 16, 21, 26,  2,  7, 12, 17, 22,
       27,  3,  8, 13, 18, 23, 28,  4,  9, 14, 19, 24, 29])

In [26]:
c = b.reshape(5,6)
c

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [27]:
np.where(c % 6 == 1)

(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))